### ISSUE TITLE
Maak een document met jQueery

### ISSUE THREAD

**Issue by PierreVanvolsem** [oBoii/Mobile-Internet2#1]
Maak een document met jQueery. Als je op een paragraaf klikt komt er een alert voor .

**Comment by fdenoodt** [comment]
<!DOCTYPE html>
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
    $("p").click(function(){
        alert(this);
    });
});
</script>
</head>
<body>

<p>If you click on me, I will disappear.</p>
<p>Click me away!</p>
<p>Click me too!</p>

</body>
</html>
